name: Build and Deploy for Development project Backend
on:
  push:
    path:
      - 'CHURNR-CRM/Backend/**'
    branches-ignore:
      - 'main'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Backend dev workflow"