name: Build and Deploy for Development project Frontend
on:
  push:
    path:
      - 'Frontend/**'
    branches-ignore:
      - 'main'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Frontend dev workflow"