name: Build and Deploy for Development project
on:
  push:
    path:
      - 'Backend/*'
    branches:
      - '*'
    branches-ignore:
      - 'main'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Backend dev workflow"