name: Build and Deploy
on:
  push:
    branches:
      - main
env: 
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install functions dependencies
        run: npm ci
        working-directory: ./Backend/functions
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: lib
          path: Backend/functions/lib
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: lib
          path: Backend/functions/lib
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHURNR_SYSTEM }}
          PROJECT_PATH: ./Backend